/**
 * The files this engine loads at runtime, and the facts about them that matter.
 *
 * The bytes ship inside the package under `assets/dewarp/` and are copied into
 * the host's public directory by `scan-copy-assets`; the host then tells the
 * library where that landed with one string, `assetBaseUrl`. So this module
 * cannot know a URL on its own — it is handed an {@link AssetUrls} and names
 * *which* of its fields belong to this engine.
 *
 * The **version in the filename** is load-bearing and survives the move: the
 * URL is content-addressed (the first 8 hex of its sha256), so it can be cached
 * immutably forever and a rebuild is a different URL rather than a stale blob in
 * someone's phone. Nothing here may ever fall back to a CDN: if the file is
 * missing the engine fails closed and the page gets the homography.
 */

import type { AssetUrls } from "../runtime-config.ts";

/**
 * The classical (Rust/WASM) engine's asset identity — the only curved-page
 * producer.
 *
 * One file, not two: no ORT session, no separate runtime wasm to version —
 * `dewarp-rs`'s own `wasm-bindgen` glue *is* the runtime. Generated by
 * `dewarp-rs/build-wasm.sh` into `wasm-manifest.json`. The constant itself is
 * declared in `runtime-config.ts`, which is what turns it into a URL, and is
 * re-exported here so the engine and its render keys keep reading the version
 * from the module that owns the engine's assets.
 */
export { DEWARP_WASM_VERSION } from "../runtime-config.ts";

/** sha256 of the vendored `.wasm`, in full. */
export const DEWARP_WASM_SHA256 =
  "2ae72e6f36d493f8627bfdedead9e742eed230dfd2c8e2f5caefbce78d45bf9a";

/**
 * Exact byte length of the **decompressed** `.wasm` — the unit a
 * `response.body` reader hands out. A progress counter fed by streamed chunks
 * must total the bytes those chunks actually sum to, not the compressed
 * `content-length` header behind a host's gzip, which is a different, smaller
 * number.
 */
export const DEWARP_WASM_BYTES = 356_065;

/**
 * What actually crosses the wire when the host serves `application/wasm`
 * gzipped — the honest number for a *human-readable* "this will download ~X"
 * sentence (`i18n.ts`'s `preview.dewarp.consent*`), which is not the same
 * question a progress counter answers and must not reuse
 * {@link DEWARP_WASM_BYTES} for it.
 */
export const DEWARP_WASM_GZIP_BYTES = 146_406;

/** The two URLs the classical engine fetches, and nothing else. */
export interface DewarpAssets {
  /** The wasm module itself, streamed by the glue's own `default()`. */
  readonly wasmUrl: string;
  /** The `wasm-bindgen --target web` glue, alongside the `.wasm` it instantiates. */
  readonly glueUrl: string;
}

/**
 * This engine's slice of the host's asset base.
 *
 * A function rather than the two constants it replaced: the base is a property
 * of the *host*, learned when the component mounts, so there is no module-level
 * moment at which a URL could honestly be computed. Everything that fetches —
 * the prefetch, the worker — takes an {@link AssetUrls} and asks here.
 */
export function dewarpAssets(urls: AssetUrls): DewarpAssets {
  return { wasmUrl: urls.dewarpWasm, glueUrl: urls.dewarpGlue };
}

/**
 * How the two URLs reach the worker: through its **name**.
 *
 * The worker cannot derive them. `import.meta.url` points at the emitted worker
 * chunk inside the host's bundle, which says nothing about where the host put
 * `assets/`, and the wasm must be fetched before the first message could carry
 * anything — so the base has to be in hand at construction. `new Worker(url,
 * { name })` is the only construction-time channel that does not touch the
 * worker's own URL: appending a query string there is rewritten by bundlers
 * that recognise `new Worker(new URL("./x.worker.ts", import.meta.url))` as a
 * pattern, and that pattern is what emits the chunk at all. `self.name` is read
 * back verbatim, costs no message round-trip, and shows up in DevTools' worker
 * list as a readable label rather than as noise.
 *
 * Kept as a pair of functions here, next to the shape they carry, so the two
 * ends cannot drift.
 */
export function encodeDewarpAssets(assets: DewarpAssets): string {
  return JSON.stringify({ wasmUrl: assets.wasmUrl, glueUrl: assets.glueUrl });
}

/**
 * The other end of {@link encodeDewarpAssets}. `null` for anything that is not
 * the pair — a worker constructed without a name, or by something that does not
 * know about this channel — which the worker reports as a structured
 * `initializing` failure rather than fetching a guess.
 */
export function decodeDewarpAssets(name: string): DewarpAssets | null {
  try {
    const value: unknown = JSON.parse(name);
    if (typeof value !== "object" || value === null) return null;
    const { wasmUrl, glueUrl } = value as Partial<DewarpAssets>;
    if (typeof wasmUrl !== "string" || typeof glueUrl !== "string") return null;
    if (wasmUrl === "" || glueUrl === "") return null;
    return { wasmUrl, glueUrl };
  } catch {
    return null;
  }
}
